/**
 * Invoice Ninja (https://invoiceninja.com).
 *
 * @link https://github.com/invoiceninja/invoiceninja source repository
 *
 * @copyright Copyright (c) 2022. Invoice Ninja LLC (https://invoiceninja.com)
 *
 * @license https://www.elastic.co/licensing/elastic-license
 */

import { useBlankClientQuery } from '$app/common/queries/clients';
import { useAllClientColumns } from '$app/pages/clients/common/hooks/useClientColumns';
import { Report } from '../../index/Reports';

export function useGetAvailableReports() {
  const { data: blankClient } = useBlankClientQuery({});
  const clientColumns = useAllClientColumns();

  const reports: Report[] = [
    {
      identifier: 'activity',
      label: 'activity',
      endpoint: '/api/v1/reports/activities',
      payload: {
        start_date: '',
        end_date: '',
        date_key: '',
        date_range: 'all',
        report_keys: [],
        send_email: false,
      },
      availableKeys: [],
    },
    {
      identifier: 'clients',
      label: 'clients',
      endpoint: '/api/v1/reports/clients',
      payload: {
        start_date: '',
        end_date: '',
        date_key: '',
        date_range: 'all',
        report_keys: [],
        send_email: false,
        filters: [],
      },
      section: 'data',
      availableKeys: Object.values(clientColumns),
      blankEntity: blankClient,
      entityName: 'client',
    },
    {
      identifier: 'client_contacts',
      label: 'client_contacts',
      endpoint: '/api/v1/reports/contacts',
      payload: {
        start_date: '',
        end_date: '',
        date_key: '',
        date_range: 'all',
        report_keys: [],
        send_email: false,
        filters: [],
      },
      section: 'data',
      availableKeys: Object.values(clientColumns),
      blankEntity: blankClient,
      entityName: 'client',
    },
    {
      identifier: 'credits',
      label: 'credits',
      endpoint: '/api/v1/reports/credits',
      payload: {
        start_date: '',
        end_date: '',
        date_key: '',
        date_range: 'all',
        report_keys: [],
        send_email: false,
      },
      section: 'data',
    },
    {
      identifier: 'documents',
      label: 'documents',
      endpoint: '/api/v1/reports/documents',
      payload: {
        start_date: '',
        end_date: '',
        date_key: '',
        date_range: 'all',
        report_keys: [],
        send_email: false,
      },
      section: 'data',
    },
    {
      identifier: 'expenses',
      label: 'expenses',
      endpoint: '/api/v1/reports/expenses',
      payload: {
        start_date: '',
        end_date: '',
        date_key: '',
        date_range: 'all',
        report_keys: [],
        send_email: false,
      },
      section: 'data',
    },
    {
      identifier: 'invoices',
      label: 'invoices',
      endpoint: '/api/v1/reports/invoices',
      payload: {
        start_date: '',
        end_date: '',
        date_key: '',
        date_range: 'all',
        report_keys: [],
        send_email: false,
        status: '',
      },
      section: 'data',
    },
    {
      identifier: 'invoice_items',
      label: 'invoice_items',
      endpoint: '/api/v1/reports/invoice_items',
      payload: {
        start_date: '',
        end_date: '',
        date_key: '',
        date_range: 'all',
        report_keys: [],
        send_email: false,
      },
      section: 'data',
    },
    {
      identifier: 'quotes',
      label: 'quotes',
      endpoint: '/api/v1/reports/quotes',
      payload: {
        start_date: '',
        end_date: '',
        date_key: '',
        date_range: 'all',
        report_keys: [],
        send_email: false,
      },
      section: 'data',
    },
    {
      identifier: 'quote_items',
      label: 'quote_items',
      endpoint: '/api/v1/reports/quote_items',
      payload: {
        start_date: '',
        end_date: '',
        date_key: '',
        date_range: 'all',
        report_keys: [],
        send_email: false,
      },
      section: 'data',
    },
    {
      identifier: 'recurring_invoices',
      label: 'recurring_invoices',
      endpoint: '/api/v1/reports/recurring_invoices',
      payload: {
        start_date: '',
        end_date: '',
        date_key: '',
        date_range: 'all',
        report_keys: [],
        send_email: false,
      },
      section: 'data',
    },
    {
      identifier: 'payments',
      label: 'payments',
      endpoint: '/api/v1/reports/payments',
      payload: {
        start_date: '',
        end_date: '',
        date_key: '',
        date_range: 'all',
        report_keys: [],
        send_email: false,
      },
      section: 'data',
    },
    {
      identifier: 'products',
      label: 'products',
      endpoint: '/api/v1/reports/products',
      payload: {
        start_date: '',
        end_date: '',
        date_key: '',
        date_range: 'all',
        report_keys: [],
        send_email: false,
      },
      section: 'data',
    },
    {
      identifier: 'product_sales',
      label: 'product_sales',
      endpoint: '/api/v1/reports/product_sales',
      payload: {
        start_date: '',
        end_date: '',
        client_id: '',
        date_key: '',
        date_range: 'all',
        report_keys: [],
        send_email: false,
      },
      section: 'sales',
    },
    {
      identifier: 'tasks',
      label: 'tasks',
      endpoint: '/api/v1/reports/tasks',
      payload: {
        start_date: '',
        end_date: '',
        date_key: '',
        date_range: 'all',
        report_keys: [],
        send_email: false,
      },
      section: 'data',
    },
    {
      identifier: 'profitloss',
      label: 'profitloss',
      endpoint: '/api/v1/reports/profitloss',
      payload: {
        start_date: '',
        end_date: '',
        date_key: '',
        date_range: 'all',
        report_keys: [],
        send_email: false,
        is_expense_billed: false,
        is_income_billed: false,
        include_tax: false,
      },
      section: 'company',
    },
    {
      identifier: 'ar_detailed',
      label: 'ar_detailed',
      endpoint: '/api/v1/reports/ar_detail_report',
      payload: {
        start_date: '',
        end_date: '',
        date_key: '',
        date_range: 'all',
        report_keys: [],
        send_email: false,
        is_expense_billed: false,
        is_income_billed: false,
        include_tax: false,
      },
      section: 'receivables',
    },
    {
      identifier: 'ar_summary',
      label: 'ar_summary',
      endpoint: '/api/v1/reports/ar_summary_report',
      payload: {
        start_date: '',
        end_date: '',
        date_key: '',
        date_range: 'all',
        report_keys: [],
        send_email: false,
        is_expense_billed: false,
        is_income_billed: false,
        include_tax: false,
      },
      section: 'receivables',
    },
    {
      identifier: 'client_balance',
      label: 'client_balance',
      endpoint: '/api/v1/reports/client_balance_report',
      payload: {
        start_date: '',
        end_date: '',
        date_key: '',
        date_range: 'all',
        report_keys: [],
        send_email: false,
        is_expense_billed: false,
        is_income_billed: false,
        include_tax: false,
      },
      section: 'receivables',
    },
    {
      identifier: 'client_sales',
      label: 'client_sales',
      endpoint: '/api/v1/reports/client_sales_report',
      payload: {
        start_date: '',
        end_date: '',
        date_key: '',
        date_range: 'all',
        report_keys: [],
        send_email: false,
        is_expense_billed: false,
        is_income_billed: false,
        include_tax: false,
      },
      section: 'sales',
    },
    {
      identifier: 'tax_summary',
      label: 'tax_summary',
      endpoint: '/api/v1/reports/tax_summary_report',
      payload: {
        start_date: '',
        end_date: '',
        date_key: '',
        date_range: 'all',
        report_keys: [],
        send_email: false,
        is_expense_billed: false,
        is_income_billed: false,
        include_tax: false,
      },
      section: 'tax',
    },
    {
      identifier: 'user_sales',
      label: 'user_sales',
      endpoint: '/api/v1/reports/user_sales_report',
      payload: {
        start_date: '',
        end_date: '',
        date_key: '',
        date_range: 'all',
        report_keys: [],
        send_email: false,
        is_expense_billed: false,
        is_income_billed: false,
        include_tax: false,
      },
      section: 'sales',
    },
  ];

  return reports;
}
